name: Regenerate Artifacts

# Controls when the action will run. Triggers the workflow on push event
# but only for the master branch, and specifically when a YAML file in 'schema' folder is modified
on:
  push:
    branches:
    - master
    paths:
    - 'schema/*.yaml'
  repository_dispatch:
    types: trigger-build-artifacts

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE
    - name: Checkout
      uses: actions/checkout@v2
      with:
        token: ${{ secrets.API_TOKEN }}

    - name: Setup Python Environment
      uses: actions/setup-python@v2
      with:
        # Version range or exact version of a Python version to use, using SemVer's version range syntax.
        python-version: 3.7
        # The target architecture (x86, x64) of the Python interpreter.
        # architecture: x64 # optional

    - name: Setup build environment
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential git wget curl
        sudo apt-get install -y openjdk-8-jre
        sudo apt-get install -y graphviz
        wget https://github.com/joelittlejohn/jsonschema2pojo/releases/download/jsonschema2pojo-1.0.2/jsonschema2pojo-1.0.2.tar.gz
        tar -xvzf jsonschema2pojo-1.0.2.tar.gz
        pip install pipenv
    - name: Generate artifacts
      run: |
        export PATH=$PATH:`pwd`/jsonschema2pojo-1.0.2/bin
        make
        cd schema && python generate_uml.py nmdc.yaml nmdc_schema_uml.png && cd ..
        if [ $? -eq 0 ]; then
          git config --global user.name "$GITHUB_NAME"
          git config --global user.email "$GITHUB_EMAIL"
          git add schema/nmdc.*
          git add schema/nmdc_schema_uml.png
          git commit -m "Regenerate artifacts from nmdc.yaml"
          git push
        else
          echo "'make' failed to finish successfully"
        fi
      env:
        GITHUB_NAME: ${{ secrets.WORKFLOW_USERNAME }}
        GITHUB_EMAIL: ${{ secrets.WORKFLOW_EMAIL }}
